name: designs
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
